name: pseudomancer_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - nextflow
  - mmseqs2
  - emboss
  - ncbi-datasets-cli
  - setuptools=70.2.0
  - wheel=0.43.0
  - requests>=2.25.0
  - pandas>=1.3.0
  - biopython>=1.79
  - pytest>=6.0.0
  - ruff
  - pip
  - pip:
    - -e .
    - sphinx
    - myst-parser
    - furo
    - sphinx-autodoc-typehints