[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pseudomancer"
version = "0.1.0"
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "MIT" }

[tool.black]
include = '\.pyi?$'
line-length = 80