name: Build and Deploy Docs

on:
  push:
    branches:
      - main
      - develop
      - sphinx-documentation

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          # Pin versions to avoid incompatibilities between Sphinx and Furo
          pip install "sphinx==7.3.7" "furo==2024.8.6" myst-parser sphinx-autodoc-typehints

      - name: Build Sphinx docs
        run: sphinx-build -b html docs/source _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          force_orphan: true
