name: pseudomancer-CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron:  '1 1 1 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: pseudomancer_env
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest
