name: pseudomancer-CI

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop
  schedule:
    - cron:  '1 1 1 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: pseudomancer_env
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
    - name: Lint with ruff
      shell: bash -l {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ruff check --select=E9,F63,F7,F82 .
        # check for other issues but don't fail the build
        ruff check . || true
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest


  docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: pseudomancer_env
          environment-file: environment.yml
          python-version: 3.12

      - name: Build Sphinx docs
        shell: bash -l {0}
        working-directory: docs
        run: |
          make html

      - name: Upload docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/html

  deploy:
    runs-on: ubuntu-latest
    needs: docs
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: html-docs
          path: docs/build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
